name = "ttypty"

preprocess = [
  { call = "sed", arguments = ["-i", "s/echo \"set timeout=1\"/echo \"set timeout=0\"/g", "{{ $.Scripts }}/mkimg.base.sh"] },
  { call = "sed", arguments = ["-i", "s/linux-firmware wireless-regdb/linux-firmware-none/g", "{{ $.Scripts }}/mkimg.base.sh"] },
]

[variables.world]
call = "cat"
arguments = ["world"]

[repository]
url = "https://dl-cdn.alpinelinux.org/alpine/{{ $.Tag }}"
repositories = [
  "main",
  "community"
] 

[source]
template = """
profile_{{ $.Name }}() {
  hostname="alpine.{{ $.Name }}"
  modloop_sign=yes
  initfs_cmdline="modules=loop,squashfs,sd-mod,usb-storage quiet"
  initfs_features="ata base bootchart cdrom ext4 nvme squashfs usb virtio"
  grub_mod="all_video disk part_gpt part_msdos linux normal configfile search search_label efi_gop fat iso9660 cat echo ls test true help gzio"
  profile_abbrev="std"
  image_ext="iso"
  output_format="iso"
  title='{{ $.Name }}'
  desc='{{ $.Name }} personal spin iso'
  kernel_flavors='virt'
  profile_abbrev='{{ $.Name }}'
  arch='{{ $.Arch }}'
  kernel_addons=
  apks="{{range $i, $a := index $.Commands "world" }} {{ $a }}{{end}}"
}
"""
