[obu]
modules = ["overlay"]
rootbind = "/overlay"

directories = [
  "bin",
  "lib",
  "root",
  "sbin",
  "srv",
  "opt",
  "usr"
]

tracked = []

[device]
source = "/dev/disk/by-uuid/<uuid>"
mount = "/media/overlay"
