name: "alpine-iso"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    name: build
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: "setup go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: "install deps"
        run: apk add git just doas syslinux
      - name: "build tools"
        run: just
      - name: "setup keys"
        env:
          IMAGE_PRIVKEY: ${{secrets.ALPINE_IMAGE_RSA_KEY}}
          IMAGE_PUBKEY: ${{secrets.ALPINE_IMAGE_RSA_KEY_PUBLIC}}
          IMAGE_KEY_NAME: ${{vars.ALPINE_IMAGE_KEY_NAME}}
        run: |
          mkdir -p "$HOME/.abuild"
          echo "$IMAGE_PRIVKEY" > "$HOME/.abuild/$IMAGE_KEY_NAME"
          echo "$IMAGE_PUBKEY" > "$HOME/.abuild/$IMAGE_KEY_NAME.pub"
          echo "PACKAGER_PRIVKEY=\"$HOME/.abuild/$IMAGE_KEY_NAME\"" > "$HOME/.abuild/abuild.conf"
          cp "$HOME/.abuild/$IMAGE_KEY_NAME.pub" "/etc/apk/keys/"
      - name: "run image build"
        run: cd alpine && just admin= deps build
      - name: "archive outputs"
        uses: actions/upload-artifact@v4
        with:
          name: alpine-image
          path: alpine/build/*.iso
