name: "build"

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    name: iso
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: "deps"
        run: apk add make
      - name: "setup-keys"
        env:
          ISO_PRIVKEY: ${{secrets.ALPINE_ISO_RSA_KEY}}
          ISO_PUBKEY: ${{secrets.ALPINE_ISO_RSA_KEY_PUBLIC}}
          ISO_KEY_NAME: ${{secrets.ALPINE_ISO_KEY_NAME}}
        run: |
          mkdir -p "$HOME/.abuild"
          echo "$ISO_PRIVKEY" > "$HOME/.abuild/$ISO_KEY_NAME"
          echo "$ISO_PUBKEY" > "$HOME/.abuild/$ISO_KEY_NAME.pub"
          echo "PACKAGER_PRIVKEY=\"$HOME/$ISO_KEY_NAME\"" > "~/.abuild/abuild.conf"
          ls "$HOME/.abuild"
