name: "build"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    name: iso
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: "setup go"
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: "install deps"
        run: apk add git make alpine-sdk mtools dosfstools alpine-conf syslinux xorriso squashfs-tools grub grub-efi doas
      - name: "setup keys"
        env:
          ISO_PRIVKEY: ${{secrets.ALPINE_ISO_RSA_KEY}}
          ISO_PUBKEY: ${{secrets.ALPINE_ISO_RSA_KEY_PUBLIC}}
          ISO_KEY_NAME: ${{vars.ALPINE_ISO_KEY_NAME}}
        run: |
          mkdir -p "$HOME/.abuild"
          echo "$ISO_PRIVKEY" > "$HOME/.abuild/$ISO_KEY_NAME"
          echo "$ISO_PUBKEY" > "$HOME/.abuild/$ISO_KEY_NAME.pub"
          echo "PACKAGER_PRIVKEY=\"$HOME/.abuild/$ISO_KEY_NAME\"" > "$HOME/.abuild/abuild.conf"
          cp "$HOME/.abuild/$ISO_KEY_NAME.pub" "/etc/apk/keys/"
      - name: "run build"
        run: make
      - name: "archive outputs"
        uses: actions/upload-artifact@v4
        with:
          name: alpine-iso
          path: "build/"
