name: "iso"

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  builds:
    runs-on: ubuntu-latest
    name: build
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: "install base deps"
        run: apk add git just doas syslinux
      - name: "setup keys"
        env:
          IMAGE_PRIVKEY: ${{secrets.IMAGE_RSA_KEY}}
          IMAGE_PUBKEY: ${{secrets.IMAGE_RSA_KEY_PUBLIC}}
          IMAGE_KEY: ${{vars.IMAGE_KEY_NAME}}
        run: |
          mkdir -p "$HOME/.abuild"
          echo "$IMAGE_PRIVKEY" > "$HOME/.abuild/$IMAGE_KEY"
          echo "$IMAGE_PUBKEY" > "$HOME/.abuild/$IMAGE_KEY.pub"
          echo "PACKAGER_PRIVKEY=\"$HOME/.abuild/$IMAGE_KEY\"" > "$HOME/.abuild/abuild.conf"
          cp "caports/main/cusp-keys/"*.pub "/etc/apk/keys/"
          cp "$HOME/.abuild/$IMAGE_KEY.pub" "/etc/apk/keys/"
      - name: "run image build"
        run: cd iso && just admin= deps build
      - name: "archive outputs"
        uses: actions/upload-artifact@v4
        with:
          name: cusp-image
          path: iso/build/*.iso
