name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cusp-image
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: *.iso
